[project]
name = "mistral"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu==1.11.0",
    "gradio==5.28.0",
    "llama-index==0.12.33",
    "llama-index-embeddings-mistralai==0.3.0",
    "llama-index-llms-mistralai==0.4.0",
    "llama-index-tools-tavily-research==0.3.0",
    "llama-index-vector-stores-faiss==0.3.0",
    "llama-index-vector-stores-pinecone==0.4.5",
    "notebook>=7.4.1",
]
